# Generated by Django 4.2.3 on 2023-11-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("file_mtime", models.FloatField(blank=True, null=True)),
                ("file_ctime", models.FloatField(blank=True, null=True)),
                ("file_extension", models.CharField(blank=True, max_length=255)),
                ("file_md5", models.CharField(blank=True, max_length=255, null=True)),
                ("file_path", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
