# Generated by Django 4.2.3 on 2023-12-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("mtime", models.FloatField(blank=True, null=True)),
                ("ctime", models.FloatField(blank=True, null=True)),
                ("extension", models.CharField(blank=True, max_length=255)),
                ("hash_md5", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hash_blake2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("full_path", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
