# Generated by Django 4.2.3 on 2024-09-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.IntegerField(blank=True, null=True)),
                ("file_id", models.IntegerField(blank=True, null=True)),
                ("full_path", models.TextField(blank=True, null=True)),
                (
                    "hash_blake2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hash_md5", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("mtime", models.FloatField(blank=True, null=True)),
                ("ctime", models.FloatField(blank=True, null=True)),
                ("extension", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
