stages:
  - push-gitlab
  - push-docker

build-push-image-gitlab:
  image: docker

  services:
    - docker:dind

  stage: push-gitlab

  variables:
    CI_IMAGE: $CI_REGISTRY_IMAGE:latest

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_IMAGE -f docker/django/Dockerfile .
    - docker push $CI_IMAGE

build-push-image-docker:
  image: docker

  services:
    - docker:dind

  stage: push-docker

  variables:
    CI_IMAGE: jasonwu070721/duplicate_finder_api_django:latest
    IMAGE_REGISTRY: docker.io

  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $IMAGE_REGISTRY
  script:
    - docker build -t $CI_IMAGE -f docker/django/Dockerfile .
    - docker push $CI_IMAGE
