stages:
  - push

build-push-image:
  image: docker

  services:
    - docker:dind

  stage: push

  variables:
    CI_IMAGE: $CI_REGISTRY_IMAGE:latest
    GITLAB_REGISTRY_USERNAME: jasonwu

  before_script:
    - docker login $CI_REGISTRY -u $GITLAB_REGISTRY_USERNAME -p $GITLAB_REGISTRY_PASSWORD
  script:
    - docker build -t $CI_IMAGE .
    - docker push $CI_IMAGE
