stages:
  - push

build-push-image:
  image: docker

  services:
    - docker:dind

  stage: push

  variables:
    CI_IMAGE: $CI_REGISTRY_IMAGE:latest
    GITLAB_REGISTRY_USERNAME: jasonwu

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_IMAGE .
    - docker push $CI_IMAGE
