stages:
  - push-gitlab
  - push-docker

build-push-image-gitlab:
  image: docker

  services:
    - docker:dind

  stage: push-gitlab

  variables:
    CI_DJANGO_IMAGE: $CI_REGISTRY_IMAGE/duplicate-finder-api-django:latest
    CI_CELERY_IMAGE: $CI_REGISTRY_IMAGE/duplicate-finder-api-celery:latest

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_DJANGO_IMAGE -f docker/django/Dockerfile .
    - docker push $CI_DJANGO_IMAGE
    - docker build -t $CI_CELERY_IMAGE -f docker/celery/Dockerfile .
    - docker push $CI_CELERY_IMAGE

build-push-image-docker:
  image: docker

  services:
    - docker:dind

  stage: push-docker

  variables:
    CI_DJANGO_IMAGE: jasonwu070721/duplicate-finder-api-django:latest
    CI_CELERY_IMAGE: jasonwu070721/duplicate-finder-api-celery:latest
    IMAGE_REGISTRY: docker.io

  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $IMAGE_REGISTRY
  script:
    - docker build -t $CI_DJANGO_IMAGE -f docker/django/Dockerfile .
    - docker push $CI_DJANGO_IMAGE
    - docker build -t $CI_CELERY_IMAGE -f docker/celery/Dockerfile .
    - docker push $CI_CELERY_IMAGE
