
services:
  api:
    build:
      dockerfile: docker/django/Dockerfile
    restart: always
    depends_on:
      - celery
      - redis
      - mysql
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ${SEARCH_PATH}:/search_data
      
  celery:
    build:
      dockerfile: docker/celery/Dockerfile
    restart: always
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    env_file:
      - .env
    volumes:
      - ./:/app
      - ${SEARCH_PATH}:/search_data
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
