version: "3.4"

services:
  api:
    build: .
    depends_on:
      - celery
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "${SEARCH_PATH}:/app/data"
      - "./db:/app/db"

  celery:
    build: .
    command: celery -A config worker -l info
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    env_file:
      - .env
    volumes:
      - "${SEARCH_PATH}:/app/data"
      - "./db:/app/db"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
