version: "3.4"

services:
  api:
    build:
      dockerfile: docker/django/Dockerfile
    depends_on:
      - celery
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "${SEARCH_PATH}:/app/data"
      - "./db:/app/db"

  celery:
    build:
      dockerfile: docker/celery/Dockerfile
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    env_file:
      - .env
    volumes:
      - "${SEARCH_PATH}:/app/data"
      - "./db:/app/db"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
