# Generated by Django 4.0.4 on 2023-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('size', models.IntegerField(null=True)),
                ('file_mtime', models.DateTimeField(null=True)),
                ('file_ctime', models.DateTimeField(null=True)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('md5', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
